//
// AnimeCharactersDataInnerCharacter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Character details */
public struct AnimeCharactersDataInnerCharacter: Codable, JSONEncodable, Hashable {

    /** MyAnimeList ID */
    public var malId: Int?
    /** MyAnimeList URL */
    public var url: String?
    public var images: CharacterImages?
    /** Character Name */
    public var name: String?

    public init(malId: Int? = nil, url: String? = nil, images: CharacterImages? = nil, name: String? = nil) {
        self.malId = malId
        self.url = url
        self.images = images
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case malId = "mal_id"
        case url
        case images
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(malId, forKey: .malId)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(images, forKey: .images)
        try container.encodeIfPresent(name, forKey: .name)
    }
}

