//
// AnimeCharactersDataInnerVoiceActorsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AnimeCharactersDataInnerVoiceActorsInner: Codable, JSONEncodable, Hashable {

    public var person: AnimeCharactersDataInnerVoiceActorsInnerPerson?
    public var language: String?

    public init(person: AnimeCharactersDataInnerVoiceActorsInnerPerson? = nil, language: String? = nil) {
        self.person = person
        self.language = language
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case person
        case language
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(person, forKey: .person)
        try container.encodeIfPresent(language, forKey: .language)
    }
}

