//
// AnimeCharactersDataInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AnimeCharactersDataInner: Codable, JSONEncodable, Hashable {

    public var character: AnimeCharactersDataInnerCharacter?
    /** Character's Role */
    public var role: String?
    public var voiceActors: [AnimeCharactersDataInnerVoiceActorsInner]?

    public init(character: AnimeCharactersDataInnerCharacter? = nil, role: String? = nil, voiceActors: [AnimeCharactersDataInnerVoiceActorsInner]? = nil) {
        self.character = character
        self.role = role
        self.voiceActors = voiceActors
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case character
        case role
        case voiceActors = "voice_actors"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(character, forKey: .character)
        try container.encodeIfPresent(role, forKey: .role)
        try container.encodeIfPresent(voiceActors, forKey: .voiceActors)
    }
}

