//
// AnimeMeta.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AnimeMeta: Codable, JSONEncodable, Hashable {

    /** MyAnimeList ID */
    public var malId: Int?
    /** MyAnimeList URL */
    public var url: String?
    public var images: AnimeImages?
    /** Entry title */
    public var title: String?

    public init(malId: Int? = nil, url: String? = nil, images: AnimeImages? = nil, title: String? = nil) {
        self.malId = malId
        self.url = url
        self.images = images
        self.title = title
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case malId = "mal_id"
        case url
        case images
        case title
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(malId, forKey: .malId)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(images, forKey: .images)
        try container.encodeIfPresent(title, forKey: .title)
    }
}

