//
// CharacterImagesWebp.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Available images in WEBP */
public struct CharacterImagesWebp: Codable, JSONEncodable, Hashable {

    /** Image URL WEBP */
    public var imageUrl: String?
    /** Small Image URL WEBP */
    public var smallImageUrl: String?

    public init(imageUrl: String? = nil, smallImageUrl: String? = nil) {
        self.imageUrl = imageUrl
        self.smallImageUrl = smallImageUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case imageUrl = "image_url"
        case smallImageUrl = "small_image_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(imageUrl, forKey: .imageUrl)
        try container.encodeIfPresent(smallImageUrl, forKey: .smallImageUrl)
    }
}

