//
// DaterangePropTo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Date Prop To */
public struct DaterangePropTo: Codable, JSONEncodable, Hashable {

    /** Day */
    public var day: Int?
    /** Month */
    public var month: Int?
    /** Year */
    public var year: Int?

    public init(day: Int? = nil, month: Int? = nil, year: Int? = nil) {
        self.day = day
        self.month = month
        self.year = year
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case day
        case month
        case year
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(day, forKey: .day)
        try container.encodeIfPresent(month, forKey: .month)
        try container.encodeIfPresent(year, forKey: .year)
    }
}

