//
// MalUrl.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Parsed URL Data */
public struct MalUrl: Codable, JSONEncodable, Hashable {

    /** MyAnimeList ID */
    public var malId: Int?
    /** Type of resource */
    public var type: String?
    /** Resource Name/Title */
    public var name: String?
    /** MyAnimeList URL */
    public var url: String?

    public init(malId: Int? = nil, type: String? = nil, name: String? = nil, url: String? = nil) {
        self.malId = malId
        self.type = type
        self.name = name
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case malId = "mal_id"
        case type
        case name
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(malId, forKey: .malId)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(url, forKey: .url)
    }
}

