//
// ModelCharacter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Character Resource */
public struct ModelCharacter: Codable, JSONEncodable, Hashable {

    /** MyAnimeList ID */
    public var malId: Int?
    /** MyAnimeList URL */
    public var url: String?
    public var images: CharacterImages?
    /** Name */
    public var name: String?
    /** Name */
    public var nameKanji: String?
    /** Other Names */
    public var nicknames: [String]?
    /** Number of users who have favorited this entry */
    public var favorites: Int?
    /** Biography */
    public var about: String?

    public init(malId: Int? = nil, url: String? = nil, images: CharacterImages? = nil, name: String? = nil, nameKanji: String? = nil, nicknames: [String]? = nil, favorites: Int? = nil, about: String? = nil) {
        self.malId = malId
        self.url = url
        self.images = images
        self.name = name
        self.nameKanji = nameKanji
        self.nicknames = nicknames
        self.favorites = favorites
        self.about = about
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case malId = "mal_id"
        case url
        case images
        case name
        case nameKanji = "name_kanji"
        case nicknames
        case favorites
        case about
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(malId, forKey: .malId)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(images, forKey: .images)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(nameKanji, forKey: .nameKanji)
        try container.encodeIfPresent(nicknames, forKey: .nicknames)
        try container.encodeIfPresent(favorites, forKey: .favorites)
        try container.encodeIfPresent(about, forKey: .about)
    }
}

