//
// PaginationPlusPaginationItems.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PaginationPlusPaginationItems: Codable, JSONEncodable, Hashable {

    public var count: Int?
    public var total: Int?
    public var perPage: Int?

    public init(count: Int? = nil, total: Int? = nil, perPage: Int? = nil) {
        self.count = count
        self.total = total
        self.perPage = perPage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case count
        case total
        case perPage = "per_page"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(count, forKey: .count)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encodeIfPresent(perPage, forKey: .perPage)
    }
}

