//
// PeopleImagesJpg.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Available images in JPG */
public struct PeopleImagesJpg: Codable, JSONEncodable, Hashable {

    /** Image URL JPG */
    public var imageUrl: String?

    public init(imageUrl: String? = nil) {
        self.imageUrl = imageUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case imageUrl = "image_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(imageUrl, forKey: .imageUrl)
    }
}

